/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ms3test.csvimport.mahilum.ui;

import static com.ms3test.csvimport.mahilum.controllers.ColumnsController.importCSV;
import com.ms3test.csvimport.mahilum.tools.Loader;
import com.ms3test.csvimport.mahilum.tools.SharedValues;
import java.awt.Component;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author marrycute
 */
public class ImportCSVJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImportCSVJFrame
     */
    public ImportCSVJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFilename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBrowse.setText("Browse");
        btnBrowse.setName("btnBrowse"); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel1.setText("Select CSV");

        txtFilename.setEditable(false);
        txtFilename.setName("txtFilename"); // NOI18N

        jLabel2.setText("Logs:");

        txtLogs.setColumns(20);
        txtLogs.setRows(5);
        jScrollPane1.setViewportView(txtLogs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse))
                            .addComponent(jScrollPane1))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser dlgFileChooser = new JFileChooser();
        
        FileFilter filter = new FileNameExtensionFilter("CSV file", "csv");
        dlgFileChooser.setAcceptAllFileFilterUsed(false);
        dlgFileChooser.addChoosableFileFilter(filter);
        int returnVal = dlgFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = dlgFileChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            // String pathString = file.getPath();
            //String filename = file.getName();
            // Path path = file.toPath();
            txtFilename.setText(path);
            // importCSV(path);
            
            
            Worker worker = new Worker(path, this);
                try {
                    worker.execute();
                } catch (Exception e) {
                    e.printStackTrace();
            }            
            
            /*
            Loader loader = new Loader(path, this);
            SwingWorker worker = loader.createWorker();
         
            worker.execute();
            
             while (!worker.isDone()) {
            // Show Progress
            try {
                int iProgress = worker.getProgress();
                int message = worker.getState().
                System.out.println("Progress %" + iProgress);
                Thread.sleep(500);
            }
            catch (Exception ex) {
                // System.err.println(ex);
            }\*/
        }
    }//GEN-LAST:event_btnBrowseActionPerformed
    
    class Worker extends SwingWorker {
        private String filename;
        private Component parent;
        public Worker(String filename, Component parent) {
            this.filename = filename;
        }
        
        protected Object doInBackground() {
            return importCSV(filename, txtLogs);
        }
        
        protected void done() {
            String message = "Done import";
            message += "\n* Processed Count: " + SharedValues.processCount;
            message += "\n* Success Count: " + SharedValues.successCount;
            message += "\n* Failed Count: " + SharedValues.errorCount;
            JOptionPane.showMessageDialog(parent, message);
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextArea txtLogs;
    // End of variables declaration//GEN-END:variables
}
